search = [
       "https://en.wikipedia.org",
       "https://es.wikipedia.org",
       "https://kagi.com/opensearch.xml",
       { name = "IMDB", search_url_template = "https://www.imdb.com/find/?ref_=opensearch&amp;q=%s" },
       { name = "Diccionario de la lengua española / Real Academia Española", search_url_template = "https://dle.rae.es/?w=%s" },
       "https://en.wiktionary.org",
       "https://es.wiktionary.org",
       { name = "Diccionari de la llengua catalana de l’IEC", search_url_template = "https://dlc.iec.cat/Results?DecEntradaText=%s" },
       { name = "Google", search_url_template = "https://www.google.com/search?q=%s" },
       "https://www.qwant.com",
       "https://ca.wikipedia.org",
]
